### ISSUE TITLE
Broken icons when falling back to hicolor icon theme - effects arch and linux mint tested

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#129]
Hi Joshua
thanks for the great support.
When installing a clean linux mint.
Applying your script.
Numix-circle is just fine.
Ardis Icon revisited theme is just fine.
But Mint-x theme (standard theme) is broken.

Somehow the icons do not show up although I can find the following icons in
/usr/share/icons/hicolor/48x48/apps

mintbackup
mintNanny
MintUpdate
mintUpload
software-manager
software-sources

all without extensions.

I included a picture for you to see.

Bottom-line now is that these programs are void of icons in the menu.

http://imgur.com/2orJFGh

**Comment by Foggalong** [comment]
Steps for troubleshooting this

* Are all the icons, with the correct names, definitely in `/usr/share/icons/hicolor/48x48/apps`?
* Are the icon lines in all of the relevant .desktop files changed to the correct name?
* Are all the icons needed located in Mint-X?

**Comment by erikdubois** [comment]
I made a movie so you can better see what is happening here on my end.
It is good to point out that we can revert the situation with the script and option -r.


1. yes
2. yes
3. ? none present ? not sure what you mean by this

It is as if it does not look at this map /usr/share/icons/hicolor/48x48/apps. Or is the fact that there is no extension behind it relevant. I did put an extension behind and nothing happened though.

**Comment by Foggalong** [comment]
3. The Mint-X icon theme, located in `/usr/share/icons/Mint-X` - check to see if they actually have their own icons covered

**Comment by erikdubois** [comment]
can you see this in the movie at the end

**Comment by erikdubois** [comment]
there is an update-manager.png in the map /usr/share/icons/Mint-X

**Comment by erikdubois** [comment]
none with our names

**Comment by Foggalong** [comment]
ahh, I see what you mean. have you managed to find any other icon themes which have this problem?

**Comment by erikdubois** [comment]
I just went over all the icon themes

Starting with
default
gnome
hicolor
highcontrast
mint -x and all the colors
Numix
Numix light

all of the icons from the movie are gone.

Numix circle and Numix circle light work like they should.

**Comment by erikdubois** [comment]
i am not sure where to look. Should the icons be copied else where ? Probably...

**Comment by Foggalong** [comment]
@palob @dirtydancing can either of you replicate this?

**Comment by erikdubois** [comment]
at least we saw that you have to make some more adaptions for the Numix and Numix light to fully work.

Trials with update manager icon

1. put the icon in mint-x apps 48
2. put the icon in gnome apps 48

Nothing seems to work.
Went to look into the code of mint update on github
plenty of hardcoded links there

**Comment by erikdubois** [comment]
bug indeed 
i give up for today

**Comment by palob** [comment]
Cleaning the icon cache by removing ``~/.thumbnails`` and ``~/.cache/thumnails`` might help.

It doesn't reaaly matter whether or not the icons show up in ``/usr/share/applications``. For reasons I don't know some icons don't show up there when otherwise everything's fine.

**Comment by Foggalong** [comment]
Oooo, good idea! I'd not thought about cache updating.

That's a good point too - @erikdubois, are the icons showing up in the Cinnamon menu?

**Comment by dirtydancing** [comment]
@Foggalong Huh? Never used Mint, and so far never used the hardcode fixer, so I guess I will have to pass on this one :) Anyways, if I can do anything useful here with Arch/GNOME, just let me know.

**Comment by erikdubois** [comment]
Ok i tried removing the thumbnails but only directory ~/.cache/thumbnails was present. 42.000 thumbnails gone
No difference.
Then i thought were else are there cache files..

I stumbled upon the following folder : 

/home/erik/.local/share/icons/hicolor/48x48/apps

Here there was one icon from google. Changed that name quickly to mintUpdate and what do you know it shows up in the cinnamon menu now as a nice blue "G" from google icon.

**Comment by erikdubois** [comment]
I think i found it.
The difference between computers is the extension .png or .svg.
Solution : 
In stead of copying the icons to /usr/share
copy to 
~/.local/share/icons/hicolor/48x48/apps

I had to make the complete path "icons/hicolor/48x48/apps" in the other computer where I wanted to reproduce it.

Name all icons with some extension. I tried .svg and all icons show up in 
all the missing icon themes.

default
gnome
hicolor
highcontrast
mint -x and all the colors
Numix
Numix light

Numix circle and circle light
Ardis icon theme revisited 
take their normal icons.  Great

I will try now on linux mint mate 17.1.

**Comment by erikdubois** [comment]
tried it on linux mate 17.1
the solution can be reproduced
see image
http://imgur.com/RCLYfue

**Comment by palob** [comment]
So are the files located in ``~/.local/share/icons/hicolor/48x48/apps`` in the last screenshot also present in ``usr/share/icons/hicolor/48x48/apps`` by default? And what's the size, is it really 48px X 48p?

**Comment by erikdubois** [comment]
They are also present in usr/share/icons/hicolor/48x48/apps
I copied the icons to the new folder
/home/erik/.local/share/icons/hicolor/48x48/apps

and no not all of them are 48x48 as you can see in the picture

http://imgur.com/vasBnLM

**Comment by erikdubois** [comment]
Tried deleting the icons in usr/share/icons/hicolor/48x48/apps
This has no effect. Icons are still showing up because of them being in folder
/home/erik/.local/share/icons/hicolor/48x48/apps

**Comment by palob** [comment]
Yeah, ``~/.local/share`` generally overrides ``/usr/share``. What happens if you delete the icons from ``~/.local/share/icons/hicolor/48x48/apps`` and copy the ones from ``/usr/share/icons/hicolor/48x48/apps`` which aren't sized 48x48 into the subfolders of their actual size?

**Comment by erikdubois** [comment]
is this what you mean
http://imgur.com/BCV5Hw4

**Comment by palob** [comment]
Yep, but ``/usr/share`` instead of ``~/.local/share``.

**Comment by erikdubois** [comment]
where exactly should I put it
I suppose hicolor?
/usr/share/icons/hicolor

**Comment by erikdubois** [comment]
1. New installation of Linux mint 17.1 cinnamon x64
All icons are just fine (Mint-X)

2. Installing numix-circle via
sudo add-apt-repository ppa:numix/ppa
sudo apt-get update
sudo apt-get install numix-icon-theme-circle

Installed but message was "gtk-update-icon-cache: The generated cache was invalid."

Selecting Numix-circle as icon set

Screenshot of all the icons that do not follow the iconset from numix before running the fix
http://imgur.com/VcRBt3k

Overview of the icons that are not Numix Circle icons /usr/share/applications and cinnamon menu

Backup Tool
Domain Blocker
Driver Manager
GDebi Package Installer
Reactivate HP installer (not in menu)
Software Manager
Software Manager (yes twice)
Software Sources
Update Manager
Upload Manager
USB Image Writer (not important mintstick-kde.desktop) does not show in menu
USB Stick formatter (not important mintstick-format-kde.desktop) does not show in menu


3 Running fix.sh now

Result
G: Fixing HP Printer...
G: Fixing Mint Backup...
G: Fixing Mint Backup...
G: Fixing Mint Drivers...
G: Fixing Mint Nanny...
G: Fixing Mint Software Manager...
G: Fixing Mint Software Sources...
G: Fixing Mint Update Manager...
G: Fixing Mint Upload Manager...
G: Fixing Python (v2.7)...
G: Fixing Python (v3.4)...

4. Checking result 

Switching icons before checking - Software Manager was not changed in cinnamon menu.
Did no icon cache update!

http://imgur.com/hQ0jUfO

Backup Tool  FIXED
Domain Blocker  NO ICON
Driver Manager  FIXED
GDebi Package Installer NOT NUMIX ICON
Reactivate HP installer (not in menu)  FIXED
Software Manager  FIXED
Software Manager (yes twice)
Software Sources (different look in cinnamon menu then in /usr/share/applications ? cache?
Update Manager NO ICON
Upload Manager NO ICON

VLC is rounded icon in /usr/share/applications and NOT in menu cinnamon
http://imgur.com/zOYm8fN


5. getting the fixes we made already from github

Running this script. Please some feed-back if this is ok

SCRIPT START
sudo rm -rf /usr/share/icons/Numix-Circle/
sudo rm -rf /usr/share/icons/Numix-Circle-Light/
sudo rm -rf /usr/share/icons/Numix/
sudo rm -rf /usr/share/icons/Numix-Light/



sudo git clone https://github.com/numixproject/numix-icon-theme.git 
sudo git clone https://github.com/numixproject/numix-icon-theme-circle.git 

sudo cp -r numix-icon-theme/Numix /usr/share/icons/
sudo cp -r numix-icon-theme/Numix-Light /usr/share/icons/
sudo cp -r numix-icon-theme-circle/Numix-Circle /usr/share/icons/
sudo cp -r numix-icon-theme-circle/Numix-Circle-Light /usr/share/icons/

sudo gtk-update-icon-cache /usr/share/icons/Numix/
sudo gtk-update-icon-cache /usr/share/icons/Numix-Light/
sudo gtk-update-icon-cache /usr/share/icons/Numix-Circle/
sudo gtk-update-icon-cache /usr/share/icons/Numix-Circle-Light/

sudo rm -rf numix-icon-theme-circle
sudo rm -rf numix-icon-theme

SCRIPT END

Result

Cloning into 'numix-icon-theme'...
remote: Counting objects: 41436, done.
remote: Compressing objects: 100% (130/130), done.
remote: Total 41436 (delta 91), reused 0 (delta 0), pack-reused 41304
Receiving objects: 100% (41436/41436), 28.45 MiB | 8.76 MiB/s, done.
Resolving deltas: 100% (25279/25279), done.
Checking connectivity... done.
Cloning into 'numix-icon-theme-circle'...
remote: Counting objects: 25909, done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 25909 (delta 35), reused 0 (delta 0), pack-reused 25815
Receiving objects: 100% (25909/25909), 23.54 MiB | 7.64 MiB/s, done.
Resolving deltas: 100% (15071/15071), done.
Checking connectivity... done.
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.


6. checking again

First switching between icon set (just to be sure)
Not mentioning the ones that are still fixed.

Domain Blocker  NO ICON - IS NOW FIXED
GDebi Package Installer NOT NUMIX ICON - STILL NOT NUMIX ICON
Software Sources IS NOW FIXED
Update Manager NO ICON  - IS NOW FIXED
Upload Manager NO ICON - IS NOW FIXED

VLC is back as it should be - round icon from numix

This is the result up to now.
Gdebi installer is the only one that is not a numix circle icon.
I pointed mine to ../app/gdebi.svg (i think a nice red debian curl)
http://imgur.com/QuJU3T4

7. If however you change back to the general theme MINT-X (green one).

http://imgur.com/9XkbTbo

Missing icons are now :

Backup tool
Domain blocker
Software Manager
Update Manager
Upload Manager

Both in cinnamon menu and /usr/share/applications

8. Making use of our 'solution'
and copying the missing icons from

/usr/share/icons/hicolor/48x48/apps
mintbackup
mintNanny
mintUpdate
mintUpload
software-manager

http://imgur.com/v11jApW

to 

/home/erik/.local/share/icons/hicolor/48x48/apps

Without extension they still do not show up.


http://imgur.com/34487UQ

Now putting png behind the icons.
Everything shows up again in the Mint-X theme

http://imgur.com/mvaCoAu

Done

I hope all this work makes clear what the problem is.
Hope you can analyze the situation to make the script work even better.

If you have any questions I will see them put up. Contact me via google + or any other channel.
Cheers for now.

**Comment by palob** [comment]
TL;DR
Could you summarise in short what exactly is the issue?

Please note that for troubleshooting it is highly advisable to install the Numix icon themes from the latest git rather than using the PPA which is outdated currently.

What do you mean by *Now putting png behind the icons*?
Modifying the hardcode fixer script in a way it changes the icon name to *<<icon_name>>.png* would defeat it's purpose of being file type agnostic.

Maybe it's best to report the issue [upstream](https://github.com/linuxmint/mint-x-icons) and ask the Mint developers not to hardcode their icon paths.

**Comment by palob** [comment]
OK, I saw you've cut off the *.png* extensions from the icons. But why?

If the icon line looks like ``Icon=iconname`` the file extension doesn't matter :)
No need to rename any files.

**Comment by palob** [comment]
Before installing anything, are the following files in ``/usr/share/icons/hicolor/<whateversize>/icons`` and/or ``/usr/share/icons/Mint-X`` ?

mintbackup
mintNanny
mintUpdate
mintUpload
software-manager

File extension doesn't matter.

If not, in order to get the default icons back with *Mint-X* you need to revert the hardcode-fixer script or paste them to one of the locations manually.

**Comment by erikdubois** [comment]
I use ppa but then i update it from github with a script.
I think I am using the latest adaptations.

earlier today i discover a way to fix the mint-x icons again after running fix.sh

You should put the icons from the hardcoded programs not in 
/usr/share/hicolor

but 

in
 
/home/erik/.local/share/icons/hicolor/48x48/apps

Only this works on linux mint cinnamon and mate (i have tested that too)
I agree that linux mint should change their coding and I have tried to get in touch about this issue with them. No succes there.

Fix.sh
in the  .desktop files you just say "Icon=mintUpdate"  - that 's great - do not change.

But the icon itself should be named mintUpdate.png then everything works

Bottomline : 

Put the five icons  in an other path/folder

/usr/share/icons/hicolor/48x48/apps
mintbackup.png
mintNanny.png
mintUpdate.png
mintUpload.png
software-manager.png

and users will not complain that the script broke their icon theme.
(I know you can do fix.sh -r but how many know this?)

**Comment by palob** [comment]
Well renaming icons or moving icons is beyond the script's scope and I don't see why it's even needed.

> But the icon itself should be named mintUpdate.png then everything works
Which icons?

**Comment by erikdubois** [comment]
I understand that the script is copying the icons from the hardcoded link to the folder 
/usr/share/icons/hicolor/48x48/apps

The original icons stay on their original places.

http://imgur.com/1azyOFm

As you can see your script works fine. The icons do arrive there although without extension as you can see.

Adding an extension in /usr/share/icons/hicolor/48x48/apps/software-manager.png DOES NOT HELP.

So I kept looking what could be the problem.

I found a solution - maybe not the best - that works.

Put the five icons that are broken not in 
usr/share/icons/hicolor/48x48/apps.
But put them here 
~/.local/share/icons/hicolor/48x48/apps

These are the 5 icons that you break if you run fix.sh.

mintbackup.png
mintNanny.png
mintUpdate.png
mintUpload.png
software-manager.png

If you like we can skype because that will be more effective.

**Comment by erikdubois** [comment]
no icons in mint-x

**Comment by palob** [comment]
Huh, AFAIK all the hardocde-fixer script does is fixing the ``Icon=`` lines in ``.desktop`` launchers.

**Comment by erikdubois** [comment]
i know it is puzzling
it is just linux mint

**Comment by erikdubois** [comment]
it just does not check the hicolor folder
or is it a cache problem?

**Comment by erikdubois** [comment]
in my quest to solve this one i have been on sites like

In order to have a place for third party applications to install their icons there should always exist a theme called "hicolor" [1]. The data for the hicolor theme is available for download at: http://www.freedesktop.org/software/icon-theme/. Implementations are required to look in the "hicolor" theme if an icon was not found in the current theme. 
https://developer.gnome.org/icon-theme-spec/
and others

so I wonder what script makes the icons in linux mint work like they do now.
If something is wrong there we can report it back to linux mint

**Comment by dirtydancing** [comment]
What is the `Inherits=` line in Mint-X icon theme? Is it `Inherits=gnome,ubuntu-mono-light,hicolor,gnome-colors-wise`? That is a somewhat unusual order, as hicolor is not last.

And where are the icons originally stored? Apparently not in Mint-X?

Just checking if there is a problem with the inheritances. Once things get puzzling, that is a place to look.

**Comment by erikdubois** [comment]
that's mine
[Icon Theme]
Name=Mint-X
Inherits=gnome,ubuntu-mono-light,hicolor,gnome-colors-wise

**Comment by erikdubois** [comment]
no they are stored in lib folders and so on

**Comment by palob** [comment]
@erikdubois Where did those icons without file name extension come from?

**Comment by dirtydancing** [comment]
Hah, we cross-posted above :) Could you try and put `hicolor` last in the inheritance line and report back if that changes anything?

**Comment by erikdubois** [comment]
i have been breaking my head over it too.
we have a solution but why does it not follow the general rule.

**Comment by erikdubois** [comment]
@palob The icons without file name extension come from the script.

**Comment by erikdubois** [comment]
@dirtydancing trying that now
will report back

**Comment by erikdubois** [comment]
@dirtydancing Could you try and put hicolor last in the inheritance line and report back if that changes anything?
Put it last and first nothing happens.

**Comment by dirtydancing** [comment]
OK, could you remove the entire `Inherits` line and check?

**Comment by erikdubois** [comment]
nope the 5 icons are still gone

**Comment by palob** [comment]
@erikdubois Alright, the script does this indeed which I wasn't aware of.

So what you propose is to generally move the icons to ``~/.local/share/icons`` and retain their file extensions?

**Comment by dirtydancing** [comment]
I see. Inheritance check completed :). We will have to look somewhere else then.

**Comment by erikdubois** [comment]
@palob unless we find an other solution - this works on cinnamon and mate
should check on xfce

**Comment by dirtydancing** [comment]
@erikdubois What are the original file names? Do they contain .png extensions?

**Comment by erikdubois** [comment]
@palob it does not even matter if you put them in 48x48 or 96x96 they show up anyhow

**Comment by erikdubois** [comment]
i wrote a script to fix icons.
Here you can see what the extensions are


# domain blocker or mintnanny
# sudo sed -i 's/\/usr\/lib\/linuxmint\/mintNanny\/icon.svg/mintnanny/g' /usr/share/applications/mintNanny.desktop
# sudo sed -i 's/\/usr\/lib\/linuxmint\/mintNanny\/icon.svg/mintnanny/g' /usr/share/applications/kde4//mintNanny.desktop
# echo "domain blocker icon fixed"
# Backup Tool icon
# sudo sed -i 's/\/usr\/lib\/linuxmint\/mintBackup\/icon.svg/mintbackup/g' /usr/share/applications/mintBackup.desktop
# sudo sed -i 's/\/usr\/lib\/linuxmint\/mintBackup\/icon.png/mintbackup/g' /usr/share/applications/mintBackup_mime.desktop
# sudo sed -i 's/\/usr\/lib\/linuxmint\/mintBackup\/icon.png/mintbackup/g' /usr/share/applications/kde4/mintBackup.desktop
# echo "backup tool icon fixed"
# mintupload
# sudo sed -i 's/\/usr\/lib\/linuxmint\/mintUpload\/icon.svg/mintupload/g' /usr/share/applications/mintupload.desktop
# sudo sed -i 's/\/usr\/lib\/linuxmint\/mintUpload\/icon.svg/mintupload/g' /usr/share/applications/kde4/mintupload.desktop
# echo "mintupload icon fixed"
# mintdrivers
# sudo sed -i 's/\/usr\/share\/icons\/hicolor\/scalable\/apps\/driver-manager.svg/driver-manager/g' /usr/share/applications/kde4/mintdrivers.desktop
# sudo sed -i 's/\/usr\/share\/icons\/hicolor\/scalable\/apps\/driver-manager.svg/driver-manager/g' /usr/share/applications/mintdrivers.desktop
# echo "mintdrivers icon fixed"
# software sources
# sudo sed -i 's/\/usr\/share\/icons\/hicolor\/scalable\/apps\/software-sources.svg/package_yast_software/g' /usr/share/applications/kde4/mintsources.desktop
# sudo sed -i 's/\/usr\/share\/icons\/hicolor\/scalable\/apps\/software-sources.svg/package_yast_software/g' /usr/share/applications/mintsources.desktop
# sudo sed -i 's/\/usr\/share\/icons\/hicolor\/scalable\/apps\/software-sources.svg/package_yast_software/g' /usr/share/applications/kde4/mintsources.desktop
# echo "software sources icon fixed"
# mintinstall or software manager
# sudo sed -i 's/\/usr\/lib\/linuxmint\/mintInstall\/icon.svg/software-manager/g' /usr/share/applications/mintInstall.desktop
# sudo sed -i 's/\/usr\/lib\/linuxmint\/mintInstall\/icon.svg/software-manager/g' /usr/share/applications/mintInstall_kde.desktop
# echo "python icon fixed"
# mintupdate
# sudo sed -i 's/\/usr\/lib\/linuxmint\/mintUpdate\/icons\/base.svg/mintUpdate/g' /usr/share/applications/mintUpdate.desktop
# echo "mintupdate icon fixed"

**Comment by erikdubois** [comment]
as you can see some are png and some are svg but all of them have 

STUPID names.

**Comment by dirtydancing** [comment]
@erikdubois I thought from what I read above that once the .png extensions are added, these icons are also displayed when they are located in `/usr/share/icons/hicolor/...`?

I figure that it would be better to keep global icon themes global and local icon themes local.

**Comment by dirtydancing** [comment]
And agreed that the names are not ideal :) Still, the name itself should not matter. I was just figuring that copying the icon file to hicolor would keep the file type extension?

**Comment by palob** [comment]
I think he said they only show up when copied to ``~/.local/share/icons`` no matter whether or not the extension is present - that's the issue as far as I understand.

**Comment by dirtydancing** [comment]
I am actually not sure what exactly is the case here, so I asked back just to be sure.

**Comment by palob** [comment]
So the vanishing file extensions might very well be a bug with the hardcode-fixer script, right?

**Comment by dirtydancing** [comment]
Yes.

**Comment by erikdubois** [comment]
ok tested it again
just to be sure
if without extension in /home/erik/.local/share/icons/hicolor/48x48/apps
it will NOT work

with extension png or svg it WILL show up

**Comment by palob** [comment]
And in ``/usr/share/icons/..`` it won't show up anyway?

**Comment by erikdubois** [comment]
incredible ?
or am i doing something wrong
learned about cache ... but can that be the issue
do you run a gtk-update-cache in the script?

**Comment by erikdubois** [comment]
may i suggest linux mint installation.... ;-)

**Comment by palob** [comment]
So what? Do they show up or not?

**Comment by erikdubois** [comment]
no they wont
but i just tried the following

sudo gtk-update-icon-cache hicolor/
again
does the script doe this ?
because now i see icons !!!

**Comment by dirtydancing** [comment]
Ah, so we apparently have an icon cache situation, always worth a look, even before the inheritances :)

**Comment by erikdubois** [comment]
and i had given all the icons the extension .png in hicolor
removing them now and testing again

**Comment by erikdubois** [comment]
ok they do need to have an extension !!!!

**Comment by dirtydancing** [comment]
Could you try a forced `gtk-update-icon-cache -f ...`, just to be sure?

**Comment by erikdubois** [comment]
i just checked 
there is no gtk-update-icon-cache in the script

**Comment by erikdubois** [comment]
Bottomline 

we can keep the folder /usr/share/icons/hicolor
but we should add 
gtk-update-icon-cache in the script at the end
and 
see that the icons have the original extension

**Comment by palob** [comment]
Should be doable :+1:

**Comment by erikdubois** [comment]
does that sum it up?
Let us give it a rest for now.
Here it is 21:19 pm. Time to watch some television.
Let me test it one more time tomorrow.

**Comment by erikdubois** [comment]
thanks @palob and @dirtydancing

**Comment by dirtydancing** [comment]
Again, could you check a forced `gtk-update-icon-cache -f ...` without the extension, just to be sure?

**Comment by erikdubois** [comment]
checking

**Comment by erikdubois** [comment]
no such luck
does nothing

**Comment by erikdubois** [comment]
sudo gtk-update-icon-cache -f hicolor/

**Comment by dirtydancing** [comment]
OK, icon cache check completed as well :) That should be it then.

**Comment by erikdubois** [comment]
like I said 
let us test it one more time.
we need to be sure before we spread the message in the linux mint community

**Comment by erikdubois** [comment]
no i am going to check it now 
give me 30 minutes

**Comment by dirtydancing** [comment]
OK. For the icon cache checks, could you then also check with a complete system restart. The icon cache can be more tricky than one might think.

Also I am wondering: does the hardcode-fixer script always remove the icon file type extension when copying the original icon to `hicolor`? Or is this only for the Mint icons in question here?

**Comment by erikdubois** [comment]
Come and look over my shoulder
to see the solution.
The bottom line solution just works and is the easiest to fix.

Give youtube some time to render. It is hd
http://youtu.be/nXcvZLlyOp0

**Comment by erikdubois** [comment]
@dirtydancing Also I am wondering: does the hardcode-fixer script always remove the icon file type extension when copying the original icon to hicolor? Or is this only for the Mint icons in question here?

I can give you an answer tomorrow.

**Comment by palob** [comment]
At the beginning the ``fix.sh`` output shows that besides the Mint stuff *HP Printer* and *Python* have been fixed.

When you show your ``/usr/share/icons/hicolor`` directory I can also spot the files ``printer`` and ``python`` without extension. 

Seems to be a real issue with the script.

**Comment by dirtydancing** [comment]
OK, I just checked with Arch/GNOME, and I could replicate this problem with Scribus: When running the hardcode-fixer script (installed via AUR), it reported that Scribus was fixed. And indeed the Numix-Circle icon for Scribus was showing. But when I switched to the default Adwaita icon theme, in the Activities app overview only a kind of "gear" icon (for no icon) was showing. Same with other icon themes such as e.g. Ozon, Paper, no Scribus icon showing.

The icon that was added to `/usr/share/icons/hicolor/48x48/apps` was named `scribus`. Without .png extension, although the file properties reported a .png file. I tried a couple of things including icon cache updates and restarting, but still, the Scribus icon did not show. Only when I renamed to `scribus.png` and did `sudo gtk-update-icon-cache /usr/share/icons/hicolor`, then the original Scribus icon was displayed with Adwaita.

**Comment by dirtydancing** [comment]
Haha, nice movie "just for you two" @erikdubois :). And as already reported above, I can confirm this.

Off topic: As this was the first time that I used the hardcode-fixer script, I noticed s.th. else: when changing the icon line, the original icon line was not kept. When I occasionally change a .desktop file manually, I tend to comment out the original icon line and then add a new one. But then again, with `-r` you can revert, and for Scribus the icon line reverted from `Icon=scribus` to `Icon=/usr/share/scribus/icons/scribus.png`. All fine, no problems here, so I did not file a separate issue/enhancement report.

**Comment by dirtydancing** [comment]
I am actually somewhat surprised that this rather "obvious" bug is only surfacing now. @erikdubois you could probably retitle this issue report to "Broken icons in other icon themes than Numix-Circle".

**Comment by palob** [comment]
Or "Icons copied without file extension".

@erikdubois Regarding you observation that  the files in ``/usr/share/icons/hicolor/..`` didn't fix the issue regardless of being with/out extension: are you sure there weren't the same files WITHOUT extension in ``$HOME/.local/share/icons/hicolor/...`` at the same time.

As I said, the local files always take precedence.

**Comment by dirtydancing** [comment]
Yeah, "Icons copied without file extension" is arguably a better title for this issue report.

**Comment by erikdubois** [comment]
@palob are you sure there weren't the same files WITHOUT extension in $HOME/.local/share/icons/hicolor/... at the same time?

yes renamed the icons folder to iconsbackup

**Comment by erikdubois** [comment]
and in the movie on a complete clean installation
i never made the .local/share/icons/hicolor

**Comment by erikdubois** [comment]
I installed a bunch of software on the computer from the movie.
These pictures end up in the folder

[Imgur](http://i.imgur.com/BNEDVim.png)

**Comment by dirtydancing** [comment]
It will be interesting to see whether an icon cache update will still be needed if the script copies the icons WITH file extension to start with.

@erikdubois The newest title "Broken icons in other themes than Numix-Circle...." is kind of misleading: E.g. for Scribus, there is no Scribus icon in either Ozon or Paper, and so also there the icon lookup went along the inheritance line to `hicolor`, whereas in Numix-Circle the icon is included, so no need to go any further along the inheritance line (I did not do further testing).

If "Broken icons..." should be in the title, arguably "Broken icons when falling back to hicolor icon theme..." would be more accurate.

**Comment by erikdubois** [comment]
title has has changed

**Comment by erikdubois** [comment]
Situation before installing a bunch of software

http://i.imgur.com/BNEDVim.png
61 icons

I installed a bunch of software on the computer from the movie.
script is here.
https://github.com/erikdubois/UltimateLinuxMint17_1/blob/master/script_to_install_Linux_mint_17_1_software_v7.sh

Situation after running the script
http://imgur.com/ASUuw79
78 icons

All programs have icons


Run fix.sh

G: Fixing Hardinfo...
G: Fixing Mint Update Manager...
G: Fixing Variety...

Only variety has no more icon.
Mint Update Manager has been fixed in former steps by adding .png

[Imgur](http://i.imgur.com/0bpoHRQ.png)
We are no at 81 icons !!

Script made 3 extra icons.
mintupdate  (there is also a mintupdate.png from previous solution - we know from experience that the .png is used)
hardinfo  (no extension but shows up in menu of mint-x and hicolor)
variety (no icon anywhere)







These pictures end up in the folder

New picture coming

**Comment by erikdubois** [comment]
editing the vartiey icon and changing it to variety.png and doing 
gkt-update-icon-cache on hicolor
shows up in menu

**Comment by erikdubois** [comment]
got rid of the exention of variety again
and ran gkt-update-icon-cache on hicolor
and it is gone in the menu

I guess we need the .png

**Comment by dirtydancing** [comment]
A follow-up question that arises from this is about the file type: As @erikdubois mentioned, some original icon files are `.png` and some are `.svg`. Yet, the icons copied to `hicolor` are always `.png`?

Usually in `hicolor`, `.svg` app icons are located in `scalable/apps`, not in a fixed size directory like `48x48/apps`. But I figure that this is just a convention; `.svg` icons should also be fine in `48x48/apps`.

**Comment by palob** [comment]
There might be another issue:
Apart from the script omitting the file extension all icons are copied to ``usr/share/icons/hicolor/48x48/apps`` or the local directory respectively regardless of their actual size. 
Can this cause icons not to be properly displayed?

**Comment by Foggalong** [comment]
@palob @erikdubois @dirtydancing The size directory the file is copied into *shouldn't* matter. All the icons having `*.png` extensions regardless of actually filetype shouldn't matter either because in theory the extensions could be anything (I've used `*.numix` as an example in another issue thread) and it would still be an image file.

**Comment by dirtydancing** [comment]
**File extension:** I checked with the Scribus (.png) icon in the Arch/GNOME activities app overview: as already tested above, the currently provided `scribus` in 48x48/apps in hicolor is not displayed when selecting the default Adwaita icon theme. Results after renaming and updating the hicolor icon cache:

`scribus.png` is displayed:

![png](https://cloud.githubusercontent.com/assets/7164227/8337640/a62ef41a-1aac-11e5-8873-ed85abed2dfd.png)

`scribus.svg` is displayed, although a little more blurry:

![svg](https://cloud.githubusercontent.com/assets/7164227/8337644/abedceda-1aac-11e5-8fc3-5adff710aef2.png)

`scribus.numix` is not displayed (same fallback "gear" icon as with `scribus`):

![numix](https://cloud.githubusercontent.com/assets/7164227/8337647/b0760850-1aac-11e5-9917-bd739ba1c157.png)

Can someone reproduce this (with whatever icon)?

**Size directory:** I agree that this should not matter. E.g. the Scribus icon is only 44x44, and yet it is displayed when located in 48x48/apps in hicolor, cf. the first two screenshots above.

**Comment by palob** [comment]
I can reproduce it with Scribus (original icon i a PNG) but I can't with SVGCleaner (original icon is a SVG). The SVGCleaner icon would show up anyway.

**Comment by dirtydancing** [comment]
Reproduced (actually not really, cf. below): when I checked with SVGCleaner (.svg), I noticed that the SVGCleaner icon did indeed show up with default Adwaita after running the hardcode-fixer script, in contrast to the Scribus (.png) icon. Both icon file copies created by the script do not have any file extension in hicolor/48x48/apps, they are only named `scribus` and `svgcleaner`.

This seems to indicate that the issue that this thread deals with only occurs when the original icon file is a .png file (or that at least there is no problem if it is a .svg file)? So far, I thought that for the Mint icons above, this applied to .png as well as to .svg icon files?

The SVGCleaner .svg icon is 96x96, again no problem with being located in the 48x48 size directory.

Screenshot with Adwaita icon theme right after running the hardcode-fixer script, no file renaming done:

![bildschirmfoto von 2015-06-25 10-57-08](https://cloud.githubusercontent.com/assets/7164227/8350976/27eaa576-1b2a-11e5-8cb7-d3c002532e84.png)

Alas, actually NO, and here is why: The original hardcoded icon line for SVGCleaner points to `/usr/share/icons/hicolor/scalable/apps/svgcleaner.svg`. This means that in this (untypical) special case, the icon is located in hicolor anyways :) So I went ahead and deleted/renamed the original SVGCleaner icon in `hicolor/scalable/apps`, and in consequence there was no icon displayed anymore with Adwaita icon theme, and after updating the hicolor icon cache I ended up with the fallback "gear" icon, just like for Scribus.

In the next step, I got similar results just like with the Scribus icon above.

Renaming to `svgcleaner.png`:

![png](https://cloud.githubusercontent.com/assets/7164227/8351645/46e2c5da-1b2f-11e5-9580-6791044343e1.png)

Renaming to `svgcleaner.svg`, noticeably more blurry (.svg might be needed in scalable):

![svg](https://cloud.githubusercontent.com/assets/7164227/8351663/625ed0ba-1b2f-11e5-886d-f28a22f0247f.png)

Renaming to `svgcleaner.numix`, again the same fallback "gear" icon as with `svgcleaner`:

![numix](https://cloud.githubusercontent.com/assets/7164227/8351676/74c94942-1b2f-11e5-83d8-e2d8970db235.png)

**Comment by palob** [comment]
Ah, OK, makes sense with SVGCleaner :)

So this indicates that the file extension is needed after all and that SVG icons should go in ``scalable`.

However the behaviour reported by @erikdubois where the icons would only work if copied to ``$HOME/.local/share/icons/...`` doesn't seem to make sense to me.

**Comment by dirtydancing** [comment]
Agreed. From what we have seen so far: A file extension is always needed. SVG icons should go into `scalable/apps`, or alternatively, `.png` might be used for all icons (including .svg) in `48x48/apps` (?).

As I understood it from above, that behaviour actually did vanish after updating the icon cache. So this aspect has already been resolved, there is no mandatory need for the local directory. @erikdubois?

**Comment by palob** [comment]
Actually copied Steam game icons get a ``.png`` appended by the script in line [161](https://github.com/Foggalong/hardcode-fixer/blob/master/fix.sh#L161).

Is there a special reason for that?

**Comment by Foggalong** [comment]
I'm not actually sure - I don' think there's any especial reason

**Comment by erikdubois** [comment]
back in office
anything I can do

**Comment by dirtydancing** [comment]
@erikdubois Yes. We have been wondering whether the behaviour you reported where the icons would only work if copied to `$HOME/.local/share/icons/hicolor` still applies to you or whether this has been resolved by the icon cache update as well (so that the icons can also be in `/usr/share/icons/hicolor`).

**Comment by erikdubois** [comment]
$HOME/.local/share/icons/hicolor was just a solution I found that worked but there is a better alternative.

I have a working computer here showing all icons NOT using the $HOME/.local/share/icons/hicolor but using the /usr/share/icons/hicolor/48x48/apps WITH .png extension (as mentioned in former post .svg is also workable). Dimensions and folder choice does not seem to matter as I read in former posts.

BUT an extension is critical for Linux Mint it seems.

**Comment by dirtydancing** [comment]
Sweet. So we all agree that these icons can be in` /usr/share/icons/hicolor` (depending on the setup).

And we all agree that there needs to be a file extension.

"Can the script keep the extensions from the original file? That would solve the issue."

Well, this is more complicated, because this would also involve the directory into which these icons are copied: Copying a .svg file as .svg into `hicolor/48x48/apps` will lead to a blurred display e.g. in GNOME Shell (e.g. Numix-Circle has a folder symlink `scalable/apps` with the target `48x48/apps` addressing that). So, .svg files would arguably need to be placed in `hicolor/scalable/apps`, whereas .png icons could be placed in the fixed size directory `48x48/apps`, arguably independent of their actual size.

**Comment by erikdubois** [comment]
Hi 
Just made a new installation script for Antergos and cinnamon on github.

https://github.com/erikdubois/AntergosCinnamon
Installed everything on there.

Then installed the Sardi icon theme.
https://github.com/erikdubois/Sardi

and the icon theme script at
https://github.com/erikdubois/themes-icons-pack

Made Sardi icon theme active and then I saw three icons did not show up correctly.

- variety
- hp icon
- hardinfo


The script fixes these icons in sardi, numix-circle but they are now broken in Adwaita or gnome icon theme.

After giving them the extension .PNG AND a gtk-update-icon cache hicolor they became visible in the menu's. I did not care to see if they started of as svg or png.

**Comment by erikdubois** [comment]
just upgraded from Linux mint cinnamon 17.1 to 17.2
Ran the script again
G: Fixing Mint Drivers...
G: Fixing Mint Software Sources...
G: Fixing Mint Update Manager...
G: Fixing Python (v2.7)...
G: Fixing Python (v3.4)...

Everything has been changed. Numix and Sardi work. Ofcourse the broken icons in adwaita or gnome icon theme remain.
